# The URL the site will be built for
base_url = "https://TIL.cafe"

# The site title and description; used in feeds by default.
title = "TIL.cafe"
description = "Grab a warm drink and let's learn stuff."

# TODO: taxonomies

generate_feed = true
# The number of articles to include in the feed. All items are included if
# this limit is not set (the default).
feed_limit = 200

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

taxonomies = [
{name = "post_type"},
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "solarized-dark"

[extra]
# Put all your custom variables here
